name: retry_bot
description: Dio interceptor Retry which makes retrying API Call When getting a timeout.
version: 1.0.1
homepage: https://github.com/flutterbots/flutterbots


environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.5
  dio: ^5.6.0

dev_dependencies:
  very_good_analysis: ^2.4.0



